"""sync_transport_and_guardian_updates

Revision ID: 00ed4aec1856
Revises: 4b5fa5320e0b
Create Date: 2026-04-27 18:18:45.952212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00ed4aec1856'
down_revision: Union[str, Sequence[str], None] = '4b5fa5320e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_workloads', sa.Column('day', sa.String(length=20), nullable=True))
    op.add_column('timetable_workloads', sa.Column('period', sa.Integer(), nullable=True))
    op.alter_column('timetable_workloads', 'teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable_workloads', 'teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('timetable_workloads', 'period')
    op.drop_column('timetable_workloads', 'day')
    # ### end Alembic commands ###
