"""add_timing_to_config_v2

Revision ID: 0fcedf47209a
Revises: 4e69d39c23f6
Create Date: 2026-04-21 12:32:56.587300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcedf47209a'
down_revision: Union[str, Sequence[str], None] = '4e69d39c23f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_configs', sa.Column('start_time', sa.String(length=20), nullable=True))
    op.add_column('timetable_configs', sa.Column('end_time', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_configs', 'end_time')
    op.drop_column('timetable_configs', 'start_time')
    # ### end Alembic commands ###
