"""add section_identifier to student

Revision ID: 140092c10f3c
Revises: 8f19f16ec511
Create Date: 2026-04-18 15:29:24.284858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140092c10f3c'
down_revision: Union[str, Sequence[str], None] = '8f19f16ec511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('section_identifier', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'section_identifier')
    # ### end Alembic commands ###
