"""Add fixed_slots and is_double

Revision ID: 175909ed74e4
Revises: 4261b31b28e0
Create Date: 2026-04-18 15:50:27.020064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '175909ed74e4'
down_revision: Union[str, Sequence[str], None] = '4261b31b28e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_configs', sa.Column('fixed_slots', sa.JSON(), nullable=True))
    op.drop_column('timetable_configs', 'name')
    op.add_column('timetable_workloads', sa.Column('is_double', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_workloads', 'is_double')
    op.add_column('timetable_configs', sa.Column('name', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('timetable_configs', 'fixed_slots')
    # ### end Alembic commands ###
