"""timetable rework

Revision ID: 1d926c2fa1ea
Revises: 0fcedf47209a
Create Date: 2026-04-22 16:23:20.336057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d926c2fa1ea'
down_revision: Union[str, Sequence[str], None] = '0fcedf47209a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_configs', sa.Column('schedule_structure', sa.JSON(), nullable=True))
    op.drop_column('timetable_configs', 'breaks')
    op.drop_column('timetable_configs', 'drill_periods')
    op.drop_column('timetable_configs', 'end_time')
    op.drop_column('timetable_configs', 'start_time')
    op.drop_column('timetable_configs', 'duration')
    op.alter_column('timetable_workloads', 'teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable_workloads', 'teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('timetable_configs', sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_configs', sa.Column('start_time', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('timetable_configs', sa.Column('end_time', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('timetable_configs', sa.Column('drill_periods', mysql.JSON(), nullable=True))
    op.add_column('timetable_configs', sa.Column('breaks', mysql.JSON(), nullable=True))
    op.drop_column('timetable_configs', 'schedule_structure')
    # ### end Alembic commands ###
