"""Add constraints to Teacher model

Revision ID: 27dd2e96c87a
Revises: 7c494ee75ef2
Create Date: 2026-04-16 17:49:22.289678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27dd2e96c87a'
down_revision: Union[str, Sequence[str], None] = '7c494ee75ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_constraints_id'), table_name='timetable_constraints')
    op.drop_table('timetable_constraints')
    op.add_column('teachers', sa.Column('constraints', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'constraints')
    op.create_table('timetable_constraints',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('day', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('period', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('timetable_constraints_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_timetable_constraints_id'), 'timetable_constraints', ['id'], unique=False)
    # ### end Alembic commands ###
