"""Add name to TimetableConfig

Revision ID: 4261b31b28e0
Revises: c375dc39f72b
Create Date: 2026-04-17 22:46:11.159483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4261b31b28e0'
down_revision: Union[str, Sequence[str], None] = 'c375dc39f72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_configs', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_configs', 'name')
    # ### end Alembic commands ###
