"""Add student invoices table

Revision ID: 4b5fa5320e0b
Revises: a9555ad73496
Create Date: 2026-04-24 17:50:39.218250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5fa5320e0b'
down_revision: Union[str, Sequence[str], None] = 'a9555ad73496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_invoices_id'), 'student_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_student_invoices_student_id'), 'student_invoices', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_invoices_student_id'), table_name='student_invoices')
    op.drop_index(op.f('ix_student_invoices_id'), table_name='student_invoices')
    op.drop_table('student_invoices')
    # ### end Alembic commands ###
