"""final sync of fee structure fields

Revision ID: 4e588e685ea8
Revises: 9f73b825f9fa
Create Date: 2026-04-28 19:14:08.244758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e588e685ea8'
down_revision: Union[str, Sequence[str], None] = '9f73b825f9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structures', sa.Column('month_from', sa.String(length=20), nullable=True))
    op.add_column('fee_structures', sa.Column('month_to', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_structures', 'month_to')
    op.drop_column('fee_structures', 'month_from')
    # ### end Alembic commands ###
