"""add_timing_settings_and_class_timing

Revision ID: 4e69d39c23f6
Revises: aabb1122ccdd
Create Date: 2026-04-20 18:16:50.047005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e69d39c23f6'
down_revision: Union[str, Sequence[str], None] = 'aabb1122ccdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_timing_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('lunch_after_period', sa.Integer(), nullable=True),
    sa.Column('lunch_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('short_break_after_period', sa.Integer(), nullable=True),
    sa.Column('short_break_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_timing_settings_id'), 'global_timing_settings', ['id'], unique=False)
    op.create_table('period_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=True),
    sa.Column('break_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_time_slots_id'), 'period_time_slots', ['id'], unique=False)
    op.add_column('school_classes', sa.Column('start_time', sa.String(length=10), nullable=True))
    op.add_column('school_classes', sa.Column('end_time', sa.String(length=10), nullable=True))
    op.add_column('school_classes', sa.Column('periods_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_classes', 'periods_per_day')
    op.drop_column('school_classes', 'end_time')
    op.drop_column('school_classes', 'start_time')
    op.drop_index(op.f('ix_period_time_slots_id'), table_name='period_time_slots')
    op.drop_table('period_time_slots')
    op.drop_index(op.f('ix_global_timing_settings_id'), table_name='global_timing_settings')
    op.drop_table('global_timing_settings')
    # ### end Alembic commands ###
