"""add_allowed_classes_to_sections

Revision ID: 56c375caa77e
Revises: 755ae9aaf728
Create Date: 2026-04-14 16:23:28.274907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c375caa77e'
down_revision: Union[str, Sequence[str], None] = '755ae9aaf728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_sections', sa.Column('allowed_classes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_sections', 'allowed_classes')
    # ### end Alembic commands ###
