"""add_fee_frequencies_and_due_columns

Revision ID: 6b8a0b54a08e
Revises: 00ed4aec1856
Create Date: 2026-04-28 15:18:23.340958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8a0b54a08e'
down_revision: Union[str, Sequence[str], None] = '00ed4aec1856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_frequencies_id'), 'fee_frequencies', ['id'], unique=False)
    op.create_index(op.f('ix_fee_frequencies_name'), 'fee_frequencies', ['name'], unique=True)
    op.add_column('fee_structures', sa.Column('due_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_structures', 'due_day')
    op.drop_index(op.f('ix_fee_frequencies_name'), table_name='fee_frequencies')
    op.drop_index(op.f('ix_fee_frequencies_id'), table_name='fee_frequencies')
    op.drop_table('fee_frequencies')
    # ### end Alembic commands ###
