"""create_subject_configs

Revision ID: 755ae9aaf728
Revises: 559b40a55bbc
Create Date: 2026-04-14 15:37:48.615259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755ae9aaf728'
down_revision: Union[str, Sequence[str], None] = '559b40a55bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_class', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_configurations_id'), 'subject_configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_configurations_id'), table_name='subject_configurations')
    op.drop_table('subject_configurations')
    # ### end Alembic commands ###
