"""add_school_models

Revision ID: 83807b24d6f5
Revises: 6e31a72de320
Create Date: 2026-04-10 13:08:04.489987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83807b24d6f5'
down_revision: Union[str, Sequence[str], None] = '6e31a72de320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('term_start_date', sa.Date(), nullable=True),
    sa.Column('term_end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_term_id'), 'academic_term', ['id'], unique=False)
    op.create_table('school_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('reg_number', sa.String(length=100), nullable=True),
    sa.Column('principal_name', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_profile_id'), 'school_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_profile_id'), table_name='school_profile')
    op.drop_table('school_profile')
    op.drop_index(op.f('ix_academic_term_id'), table_name='academic_term')
    op.drop_table('academic_term')
    # ### end Alembic commands ###
