"""add room_number to school_classes

Revision ID: 8d414c7974b7
Revises: 48c10a181867
Create Date: 2026-04-16 12:39:12.934305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d414c7974b7'
down_revision: Union[str, Sequence[str], None] = '48c10a181867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_classes', sa.Column('room_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_classes', 'room_number')
    # ### end Alembic commands ###
