"""add invoice_day to fee structures

Revision ID: 9f73b825f9fa
Revises: 84e96fba86b5
Create Date: 2026-04-28 19:11:53.781584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f73b825f9fa'
down_revision: Union[str, Sequence[str], None] = '84e96fba86b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structures', sa.Column('invoice_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_structures', 'invoice_day')
    # ### end Alembic commands ###
