"""Add finance tables

Revision ID: a9555ad73496
Revises: 1d926c2fa1ea
Create Date: 2026-04-24 12:51:14.805969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9555ad73496'
down_revision: Union[str, Sequence[str], None] = '1d926c2fa1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # These parts already executed successfully before the previous failure:
    # op.create_table('fee_categories', ...)
    # op.create_table('fee_structures', ...)
    # op.add_column('timetable_configs', ...)
    # op.drop_column('timetable_configs', 'schedule_structure')
    
    # We skip to the part that failed:
    op.alter_column('timetable_workloads', 'teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable_workloads', 'teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('timetable_configs', sa.Column('schedule_structure', mysql.JSON(), nullable=True))
    op.drop_column('timetable_configs', 'drill_periods')
    op.drop_column('timetable_configs', 'breaks')
    op.drop_column('timetable_configs', 'end_time')
    op.drop_column('timetable_configs', 'start_time')
    op.drop_column('timetable_configs', 'duration')
    op.drop_index(op.f('ix_fee_structures_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_fee_categories_name'), table_name='fee_categories')
    op.drop_index(op.f('ix_fee_categories_id'), table_name='fee_categories')
    op.drop_table('fee_categories')
    # ### end Alembic commands ###
