"""Add finance tables

Revision ID: a9555ad73496
Revises: 1d926c2fa1ea
Create Date: 2026-04-24 12:51:14.805969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9555ad73496'
down_revision: Union[str, Sequence[str], None] = '1d926c2fa1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'fee_categories' not in tables:
        op.create_table('fee_categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_fee_categories_id'), 'fee_categories', ['id'], unique=False)
        op.create_index(op.f('ix_fee_categories_name'), 'fee_categories', ['name'], unique=True)
    
    if 'fee_structures' not in tables:
        op.create_table('fee_structures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('section', sa.String(length=50), nullable=False),
        sa.Column('class_name', sa.String(length=50), nullable=False),
        sa.Column('category_name', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('frequency', sa.String(length=50), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_fee_structures_id'), 'fee_structures', ['id'], unique=False)

    # Check if column needs alteration
    # (Actually alter_column is usually okay to re-run, but let's be safe)
    op.alter_column('timetable_workloads', 'teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable_workloads', 'teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('timetable_configs', sa.Column('schedule_structure', mysql.JSON(), nullable=True))
    op.drop_column('timetable_configs', 'drill_periods')
    op.drop_column('timetable_configs', 'breaks')
    op.drop_column('timetable_configs', 'end_time')
    op.drop_column('timetable_configs', 'start_time')
    op.drop_column('timetable_configs', 'duration')
    op.drop_index(op.f('ix_fee_structures_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_fee_categories_name'), table_name='fee_categories')
    op.drop_index(op.f('ix_fee_categories_id'), table_name='fee_categories')
    op.drop_table('fee_categories')
    # ### end Alembic commands ###
