"""restore_teacher_section_link

Revision ID: bc918ced2961
Revises: 6595ef090112
Create Date: 2026-04-14 12:04:17.838689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc918ced2961'
down_revision: Union[str, Sequence[str], None] = '6595ef090112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_section_link',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['school_sections.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'section_id')
    )
    op.create_index(op.f('ix_school_sections_id'), 'school_sections', ['id'], unique=False)
    op.create_unique_constraint(None, 'school_sections', ['name'])
    op.drop_column('teachers', 'sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('sections', mysql.JSON(), nullable=True))
    op.drop_constraint(None, 'school_sections', type_='unique')
    op.drop_index(op.f('ix_school_sections_id'), table_name='school_sections')
    op.drop_table('teacher_section_link')
    # ### end Alembic commands ###
