"""Drop school_sections and teacher_link tables

Revision ID: c0d31ec1c09b
Revises: 60e29c71ca92
Create Date: 2026-04-13 16:23:36.653222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0d31ec1c09b'
down_revision: Union[str, Sequence[str], None] = '60e29c71ca92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_sections_id'), table_name='school_sections')
    op.drop_index(op.f('name'), table_name='school_sections')
    op.drop_table('school_sections')
    op.drop_table('teacher_section_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_section_link',
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['school_sections.id'], name=op.f('teacher_section_link_ibfk_1')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('teacher_section_link_ibfk_2')),
    sa.PrimaryKeyConstraint('teacher_id', 'section_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('school_sections',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'school_sections', ['name'], unique=True)
    op.create_index(op.f('ix_school_sections_id'), 'school_sections', ['id'], unique=False)
    # ### end Alembic commands ###
