"""Update timetable models for drill periods and subject names

Revision ID: f6b262be02f4
Revises: 67342f161477
Create Date: 2026-04-16 15:54:50.893155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6b262be02f4'
down_revision: Union[str, Sequence[str], None] = '67342f161477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_configs', sa.Column('drill_periods', sa.JSON(), nullable=True))
    op.add_column('timetable_workloads', sa.Column('config_id', sa.Integer(), nullable=True))
    op.add_column('timetable_workloads', sa.Column('subject_name', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('timetable_workloads_ibfk_2'), 'timetable_workloads', type_='foreignkey')
    op.create_foreign_key(None, 'timetable_workloads', 'timetable_configs', ['config_id'], ['id'])
    op.drop_column('timetable_workloads', 'subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_workloads', sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timetable_workloads', type_='foreignkey')
    op.create_foreign_key(op.f('timetable_workloads_ibfk_2'), 'timetable_workloads', 'subject_configurations', ['subject_id'], ['id'])
    op.drop_column('timetable_workloads', 'subject_name')
    op.drop_column('timetable_workloads', 'config_id')
    op.drop_column('timetable_configs', 'drill_periods')
    # ### end Alembic commands ###
