"""remove_dynamic_segment_classes

Revision ID: fd116c1ea03e
Revises: 56c375caa77e
Create Date: 2026-04-14 16:43:59.136823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd116c1ea03e'
down_revision: Union[str, Sequence[str], None] = '56c375caa77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_sections', 'allowed_classes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_sections', sa.Column('allowed_classes', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
